### ISSUE TITLE
Support for descriptions above values.

### ISSUE THREAD

**Issue by servo1x** [rapidsai/frigate#19]
It would be convenient if we could add description comments above the related value.

```yaml
# This is someKey.
someKey: value1
```

| Parameter                | Description             | Default        |
| ------------------------ | ----------------------- | -------------- |
| `someKey` |  This is someKey. | `"value1"` |

**Comment by raul1991** [comment]
For flat keys, this does sound convenient but for nested keys, it does not.
For nested keys, it feels more intuitive to add comments right next to them.

Example

- flat keys



```yaml

# foo is nice
foo.isNice : true
```

- nested keys

```yaml

foo
  isNice : true  # foo is nice

```

**Comment by jacobtomlinson** [comment]
The decision to only accept inline comments is mainly because of the way [ruaml](https://pypi.org/project/ruamel.yaml/) returns the data structure. Code and comments are given separately, and it is much harder to match comments above a line than on a line.

It also opens up questions about how we delimit lines, for example what if there are to lines above a key, should both be concatenated or just the lower one.

To keep a simple API the decision was made to accept inline comments only.
