### ISSUE TITLE
tests are currently broken

### ISSUE THREAD

**Issue by aogier** [rapidsai/frigate#50]
Hi, 5734a10ebe5688beec8971faf4734a4ddc24e964 somehow broke tests and block(ish) some work I'd like to do on project as per #48 . Could somebody please take a look pretty please? :)

**Comment by jacobtomlinson** [comment]
ping @consideRatio could you take a look?

**Comment by consideRatio** [comment]
- Hmmm #46 passed the tests run by the CI system
- I see some shell scripts in the ci folder
- What tests are failing, and how do you conclude that @aogier? Note that I have no idea how the test setup of this repo works atm, so any help onboarding me would be helpful if I'm to debug what possibly started failing post #46 merge.

**Comment by aogier** [comment]
@consideRatio : pytest run on 4153bf5d737894dd381402306456a7ba80d0de5f, fails on 5734a10ebe5688beec8971faf4734a4ddc24e964. I don't see any other test/testing tool/script anywhere else so I decided pytest was the current choice, given that when I begun coding against 4153bf5d737894dd381402306456a7ba80d0de5f tests were passing. Maybe supporting you developments w/ some tests (I could not see any) could shed some light on that?

**Comment by consideRatio** [comment]
My investigation concludes that the test is broken, and the #46 bugfix exposed the test case that should fail.

The test case chart in `frigate/tests/mockcharts/deps` includes the following dependencies listed, and has a .tgz file already in its `charts/` folder.

https://github.com/rapidsai/frigate/blob/5734a10ebe5688beec8971faf4734a4ddc24e964/frigate/tests/mockcharts/deps/Chart.yaml#L6-L9

After #46, we run `helm dep up .` in this folder, and fail because the provided repostiory example.com/frigate is not accessible - this makes sense. #46 bugfixed the failure to call `helm dep up` on the top level, and so now runs into this. The test case itself is broken I'd say.

The test case can be fixed by providing also a helm chart repo that provides the helm chart. I'm not sure if this must be provided by a webserver, or if you can just provide a index.yaml file locally. I'll trial this now and get back.

**Comment by consideRatio** [comment]
```
$ helm dep up .

Error: no repository definition for ../mockchartrepo. Please add them via 'helm repo add'
Note that repositories must be URLs or aliases. For example, to refer to the "example"
repository, use "https://charts.example.com/" or "@example" instead of
"example". Don't forget to add the repo, too ('helm repo add').
```

One can use `helm repo add` to define a local chart repo and then `helm repo update` and then reference that before running the test. Will keep going down the rabbit hole a bit further.

**Comment by consideRatio** [comment]
Hmmm, thinking further, making this test green is to around the shortcoming/bug of https://github.com/rapidsai/frigate/issues/49. It should be fine to have a `.tgz` chart pre-packaged in the charts/ folder that isn't declared in `dependencies`, then it should be detected and made part of the top level chart anyhow.

I think the bugfix here is to not mock a helm chart repo, but to remove the `dependencies` section with a fake repo. If then #49 is fixed, the test will go green again without mocking a helm chart repo as well.

https://github.com/rapidsai/frigate/blob/5734a10ebe5688beec8971faf4734a4ddc24e964/frigate/tests/mockcharts/deps/Chart.yaml#L6-L9

**Comment by aogier** [comment]
that's not how helm works: subcharts that are part of a chart, ie. are not declared in dependencies but exists under `charts/`, must be directories and not tgz, cause unknown tgz archives gets deleted on `helm dep update`. I don't think it is wise to deviate in such a significant way from the tool's, around which we build this one, behaviour.

**Comment by consideRatio** [comment]
> cause unknown tgz archives gets deleted on helm dep update

I think this is incorrect though.

```
$ helm dep up --help

Update the on-disk dependencies to mirror Chart.yaml.

This command verifies that the required charts, as expressed in 'Chart.yaml',
are present in 'charts/' and are at an acceptable version. It will pull down
the latest charts that satisfy the dependencies, and clean up old dependencies.

On successful update, this will generate a lock file that can be used to
rebuild the dependencies to an exact version.

Dependencies are not required to be represented in 'Chart.yaml'. For that
reason, an update command will not remove charts unless they are (a) present
in the Chart.yaml file, but (b) at the wrong version.
```

The last paragraph is whats relevant above.

I practically tried and verified also that a freshly created helm chart with `helm create` where I copied `simple-0.1.0.tgz` file used in tests here to its charts/ folder actually rendered the simple chart as well.

**Comment by consideRatio** [comment]
I think you have uncovered a bug in `helm` them, hmmm... I'll see if I can verify this.

In my mind, the `helm` bug would be that all .tgz files without the right version are deleted, not just those present in the Chart.yaml file and with the wrong version.

```
For that
reason, an update command will not remove charts unless they are (a) present
in the Chart.yaml file, but (b) at the wrong version.
```

```
$ ls charts/
simple-0.1.0.tgz

# now I edit Chart.yaml to include `dependencies: []`

$ helm dep up .
Saving 0 charts
Deleting outdated charts

$ ls charts/
(nothing)
```

Okay so `helm` has a bug about this to report...

---

Okay from this my conclusion is:
1. Any `.tgz` files in charts/ will be cleared by the `helm` bug, and assuming the bug is around, it can be fine to just inspect any `.tgz` files based on what is declared in `dependencies` as those will be the same.
2. #49 suggests we should also inspect folders in charts/, which still makes sense no matter what

## Back to this issue

This issue observed a `pytest` failure following #46. My investigation concludes that we have a test that is broken and #46 exposed that.

The test failure is related to declaring dependencies that can't be updated because we don't provide a valid helm chart repo.

https://github.com/rapidsai/frigate/blob/5734a10ebe5688beec8971faf4734a4ddc24e964/frigate/tests/mockcharts/deps/Chart.yaml#L6-L9

The key question is what to do about it.
- Was it wrong of #46 to call `helm dep up` on the top level chart? If so, users can be instructed to manually call `helm dep up` before the use frigate.
- Do we change the test, or change frigate's main logic?
